name: build

on:
  push: {}
  release:
    types: [published]
  workflow_dispatch: {}

permissions:
  packages: write
  contents: write
  pull-requests: write
  id-token: write

jobs:
  test_el7:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: run fixture test rpm build el7
        uses: "./el7"
        with:
          sources: "${{github.workspace}}/el7/test/sources"
          spec_file: "${{github.workspace}}/el7/test/spec/fixture.spec"
          supplement_sources: "${{github.workspace}}/el7/test/fixture.service"
  test_el8:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: run fixture test rpm build el8
        uses: "./el8"
        with:
          sources: "${{github.workspace}}/el8/test/sources"
          spec_file: "${{github.workspace}}/el8/test/spec/fixture.spec"
          supplement_sources: "${{github.workspace}}/el8/test/fixture.service"
  test_el9:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: run fixture test rpm build el9
        uses: "./el9"
        with:
          sources: "${{github.workspace}}/el9/test/sources"
          spec_file: "${{github.workspace}}/el9/test/spec/fixture.spec"
          supplement_sources: "${{github.workspace}}/el9/test/fixture.service"
