name: build

on:
  push: {}
  release:
    types: [published]
  workflow_dispatch: {}

permissions:
  packages: write
  contents: write
  pull-requests: write
  id-token: write

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: quay.io/centos/centos:stream8
      volumes:
        - my_docker_volume:/volume_mount
    steps:
      - uses: actions/checkout@v3
      - name: install build tools
        run: |
          dnf module enable -y nodejs:16;
          dnf install -y rpm-build rpmdevtools rpm-sign rpmlint git dnf-plugins-core nodejs npm make automake gcc gcc-c++ kernel-devel python3 glibc
      - name: node install
        run: npm install
      - name: node build
        run: npm run-script build
      - name: run fixture test rpm build
        run: node lib/main.js
        env:
          INPUT_SOURCES: /home/runner/work/docker-rpmbuild/docker-rpmbuild/test/sources
          INPUT_SPEC_FILE: /home/runner/work/docker-rpmbuild/docker-rpmbuild/test/spec/fixture.spec
          INPUT_SERVICE_FILE: /home/runner/work/docker-rpmbuild/docker-rpmbuild/test/fixture.service

  # build:
  #   uses: GeoNet/Actions/.github/workflows/reusable-docker-build.yml@main
  #   with:
  #     context: .
  #     dockerfile: ./Dockerfile
  #     imageName: centos8-rpmbuild
  #     platforms: 'linux/amd64,linux/arm64'
  #     push: ${{ github.ref_name == 'stream8' }}
